---
# tasks file for common
- name: Update apt cache and install prerequisites
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - python3-pip
      - nodejs
      - npm
      - emacs
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: present
  tags: [common, prerequisites]

# Ansible installation
- name: Install Ansible
  become: yes
  pip:
    name: ansible
    state: present
  tags: [common, ansible]

# GEMINI CLI installation
- name: Install Gemini CLI
  become: yes
  npm:
    name: '@google/gemini-cli'
    global: yes
    state: present
  tags: [common, gemini-cli]

- name: Add Gemini API Key to .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export GEMINI_API_KEY='{{ gemini_api_key }}'"
    create: yes
  tags: [common, gemini-cli]

# GitHub CLI Installation
- name: Create a directory for GitHub CLI
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
  tags: [common, github-cli]

- name: Download and unarchive the GitHub CLI
  unarchive:
    src: "https://github.com/cli/cli/releases/download/v2.51.0/gh_2.51.0_linux_amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  tags: [common, github-cli]

- name: Move the gh binary to the local bin directory
  copy:
    src: "/tmp/gh_2.51.0_linux_amd64/bin/gh"
    dest: "{{ ansible_env.HOME }}/.local/bin/gh"
    mode: '0755'
    remote_src: yes
  tags: [common, github-cli]

- name: Add .local/bin to .bashrc if it's not there
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH=$HOME/.local/bin:$PATH'
    regexp: '^export PATH=\$HOME\/\.local\/bin:\$PATH$'
    state: present
    create: yes
  tags: [common, github-cli]

- name: Authenticate with GitHub CLI
  shell: "echo {{ github_token }} | {{ ansible_env.HOME }}/.local/bin/gh auth login --with-token"
  args:
    chdir: "{{ ansible_env.HOME }}"
  tags: [common, github-cli]

- name: Configure git to use GitHub CLI for authentication
  shell: "{{ ansible_env.HOME }}/.local/bin/gh auth setup-git"
  args:
    chdir: "{{ ansible_env.HOME }}"
  tags: [common, github-cli]

# AWS CLI Installation
- name: Download and unarchive the AWS CLI installer
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes
  tags: [common, aws-cli]

- name: Run the AWS CLI installer
  command: /tmp/aws/install -i {{ ansible_env.HOME }}/.local/aws-cli -b {{ ansible_env.HOME }}/.local/bin
  tags: [common, aws-cli]

- name: Configure AWS CLI
  shell: |
    {{ ansible_env.HOME }}/.local/bin/aws configure set aws_access_key_id {{ aws_access_key_id }}
    {{ ansible_env.HOME }}/.local/bin/aws configure set aws_secret_access_key {{ aws_secret_access_key }}
    {{ ansible_env.HOME }}/.local/bin/aws configure set region us-east-1
  tags: [common, aws-cli]

- name: Add aliases to .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export ANSIBLE_HOME=${HOME}/ansible_local
      alias e='emacs'
      alias sb='source ~/.bashrc'
      alias eb='emacs ~/.bashrc'
      alias rmrf='rm -rf'
      alias ..='cd ..'
      alias ls="ls --color=auto --ignore='*~'"
      alias anpl='ansible-playbook -i ${ANSIBLE_HOME}/inventory/hosts ${ANSIBLE_HOME}/site.yml --vault-password-file ${ANSIBLE_HOME}/.vault_pass.txt'
      alias eantask='emacs ${ANSIBLE_HOME}/roles/common/tasks/main.yml'
    create: yes
  tags: [common, alias]